- name: install nginx
  hosts: local
  connection: local
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service: 
      name: nginx
      state: started

  - name: enable nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes